"""88 làng nghề bổ sung cho scripts/seed-craft-villages.py (tổng 100 làng).

Khác 12 làng gốc: KHÔNG đặt VR tour (VR là dịch vụ trả phí — để trống cho đúng thực tế) và
phần lớn ảnh là MINH HOẠ dòng sản phẩm (Commons ít ảnh chụp tại chính làng):
  • at    = ảnh chụp tại làng / sản phẩm của chính làng
  • illus = ảnh minh hoạ cùng dòng nghề, KHÔNG chụp tại làng — mô tả hồ sơ ghi rõ
Toạ độ là trung tâm xã/làng (gần đúng). Người đại diện là tên HƯ CẤU.
"""


def V(slug, name, province, district, ward, lat, lng, child, product, rep, title, desc, at=(), illus=()):
    return dict(slug=slug, name=name, province=province, district=district, ward=ward, lat=lat, lng=lng,
                child=child, product=product, rep=rep, title=title, desc=desc,
                at=list(at), illus=list(illus))


MORE_VILLAGES = [
    # ── Hà Nội ────────────────────────────────────────────────────────────────
    V("phu-vinh", "Làng mây tre đan Phú Vinh", "Hà Nội", "Chương Mỹ", "Phú Nghĩa", 20.928, 105.668,
      "may-tre", "Mây tre đan", "Nguyễn Văn Thịnh",
      "Đồ mây tre đan Phú Vinh — giỏ, khay, đèn và tượng đan",
      "Làng mây tre đan nổi tiếng xứ Đoài; nghệ nhân đan được cả tượng, tranh và đồ nội thất từ sợi mây, "
      "giang, tre. Sản phẩm xuất khẩu nhiều thị trường.",
      at=["Bamboo and rattan village Phu Vinh,Chuong My,Ha Noi,Viet Nam.jpg",
          "Handicraft products in Phu Vinh bamboo and rattan village, Viet Nam.jpg",
          "Handicraft products in Phu Vinh bamboo and rattan village, Ha Noi, Viet Nam.jpg"]),
    V("ha-thai", "Làng sơn mài Hạ Thái", "Hà Nội", "Thường Tín", "Duyên Thái", 20.886, 105.868,
      "son-mai", "Sơn mài", "Đặng Văn Toàn",
      "Tranh và đồ sơn mài Hạ Thái",
      "Làng sơn mài lớn ven Hà Nội: tranh, hộp, bình, khay phủ nhiều lớp sơn ta, mài thủ công và khảm "
      "vỏ trứng, xà cừ.",
      illus=["Hanoi-Atelier de peinture sur laque (1).jpg",
             "Hanoi-Atelier de peinture sur laque (3).jpg",
             "Hanoi-Pot de laque.jpg"]),
    V("quat-dong", "Làng thêu Quất Động", "Hà Nội", "Thường Tín", "Quất Động", 20.840, 105.872,
      "theu", "Tranh thêu tay", "Lê Thị Hằng",
      "Tranh thêu tay Quất Động",
      "Một trong những cái nôi của nghề thêu tay xứ Bắc; tranh phong cảnh, chân dung và đồ thêu trang trí "
      "làm hoàn toàn bằng kim chỉ.",
      illus=["Silk embroidery with Tree of Life motif from Vietnam.JPG",
             "Commissioned embroidery by Vũ Ngọc Hoánh, Chief of Lạng Sơn Province 01.jpg"]),
    V("chuyen-my", "Làng khảm trai Chuyên Mỹ", "Hà Nội", "Phú Xuyên", "Chuyên Mỹ", 20.742, 105.897,
      "cham-khac", "Khảm trai", "Trần Văn Quý",
      "Đồ gỗ khảm trai Chuyên Mỹ",
      "Làng khảm trai cổ: vỏ trai, ốc được cưa, mài, cẩn lên gỗ hoặc sơn mài thành tranh, hộp, sập, "
      "bàn ghế với hoa văn tinh xảo.",
      illus=["Khảm trai1.jpg", "Khảm trai2.jpg", "Sập khảm trai.jpg"]),
    V("xuan-la", "Làng tò he Xuân La", "Hà Nội", "Phú Xuyên", "Phượng Dực", 20.712, 105.862,
      "tuong", "Tò he", "Đặng Văn Hải",
      "Tò he Xuân La nặn từ bột gạo nhuộm màu tự nhiên",
      "Làng giữ nghề nặn tò he — con giống bằng bột gạo hấp, nhuộm màu từ lá cây, củ quả — gắn với "
      "tuổi thơ và các mùa lễ hội.",
      illus=['Making a "tò he".JPG', "Tò he.JPG", "Tò he con rồng.jpg"]),
    V("son-dong", "Làng tượng gỗ Sơn Đồng", "Hà Nội", "Hoài Đức", "Sơn Đồng", 21.048, 105.708,
      "tuong", "Tượng gỗ thờ", "Nguyễn Văn Phúc",
      "Tượng Phật, hoành phi, câu đối sơn son thếp vàng Sơn Đồng",
      "Làng chuyên tạc tượng và đồ thờ sơn son thếp vàng; sản phẩm có mặt ở nhiều đình, chùa khắp cả nước.",
      illus=["Avalokitesvara Bodhisattva statue, Mac dynasty, 16th century, crimson and gilded wood - National Museum of Vietnamese History - Hanoi, Vietnam - DSC05668.JPG",
             "Boy Buddha statue, Restored Le dynasty, 17th-18th century, crimson and gilded wood - National Museum of Vietnamese History - Hanoi, Vietnam - DSC05664.JPG"]),
    V("chang-son", "Làng quạt Chàng Sơn", "Hà Nội", "Thạch Thất", "Chàng Sơn", 21.052, 105.584,
      "may-tre", "Quạt giấy, quạt nan", "Kiều Văn Thắng",
      "Quạt nan, quạt giấy Chàng Sơn",
      "Làng nghề xứ Đoài nổi tiếng với quạt nan tre, quạt giấy vẽ tay và nhiều nghề mộc, thêu phụ trợ.",
      illus=["Bamboo Village (6923064574).jpg"]),
    V("kim-lan", "Làng gốm Kim Lan", "Hà Nội", "Gia Lâm", "Kim Lan", 20.958, 105.905,
      "gom-su", "Gốm sứ", "Phạm Văn Lộc",
      "Gốm Kim Lan — men cổ phục dựng",
      "Làng gốm ven sông Hồng có lịch sử từ thời Lý–Trần; nhiều xưởng phục dựng men gốm cổ theo "
      "hiện vật khai quật tại chính làng.",
      illus=["Cylindrical jar, ivory white glaze ceramic decorated with brown patterns - Tran dynasty, 13th-14th century AD - Vietnam National Museum of Fine Arts - Hanoi, Vietnam - DSC05363.JPG",
             "Ornamental jar, crackled glaze ceramic - Nguyen dynasty, 19th century AD - Vietnam National Museum of Fine Arts - Hanoi, Vietnam - DSC05320.JPG"]),
    V("van-ha", "Làng đồ gỗ Vân Hà", "Hà Nội", "Đông Anh", "Vân Hà", 21.150, 105.912,
      "do-go", "Đồ gỗ mỹ nghệ", "Lê Văn Cường",
      "Bình phong, tủ, sập gỗ mỹ nghệ Vân Hà",
      "Làng mộc mỹ nghệ ngoại thành Hà Nội, chuyên đồ gỗ cao cấp chạm khắc tay và giả cổ.",
      illus=["Bình Phong gỗ.jpg", "DoGo.JPG"]),
    V("thuy-ung", "Làng sừng mỹ nghệ Thụy Ứng", "Hà Nội", "Thường Tín", "Hòa Bình", 20.828, 105.860,
      "cham-khac", "Đồ sừng mỹ nghệ", "Nguyễn Văn Sáu",
      "Lược, trâm cài và đồ trang trí bằng sừng Thụy Ứng",
      "Làng nghề hàng trăm năm làm lược sừng, nay mở rộng sang trang sức, đồ lưu niệm và tượng chạm "
      "từ sừng trâu, bò.",
      illus=["Comb made of Buffalo Horn.jpg", "Water buffalo horn 01.JPG"]),
    V("nhi-khe", "Làng tiện gỗ Nhị Khê", "Hà Nội", "Thường Tín", "Nhị Khê", 20.893, 105.852,
      "do-go", "Đồ tiện gỗ", "Bùi Văn Hiển",
      "Đồ tiện gỗ Nhị Khê — quả cầu, chân đèn, đồ thờ",
      "Nghề tiện gỗ truyền thống làm con tiện, đế, chân đèn, đồ thờ và đồ trang trí với đường nét tròn đều.",
      illus=["Lamp stand with elephant, dragon, apricot, and lotus motifs, for ritual use, early 20th century, carved wood - National Museum of Vietnamese History - Hanoi, Vietnam - DSC05570.JPG"]),
    V("kieu-ky", "Làng dát vàng quỳ Kiêu Kỵ", "Hà Nội", "Gia Lâm", "Kiêu Kỵ", 21.003, 105.968,
      "kim-hoan", "Vàng bạc quỳ", "Nguyễn Văn Tiến",
      "Vàng quỳ, bạc quỳ Kiêu Kỵ để thếp tượng, đồ thờ",
      "Làng duy nhất còn giữ nghề dát vàng quỳ: vàng được đập mỏng như tờ giấy để thếp tượng, hoành phi, "
      "đồ thờ trong các đình chùa.",
      illus=["Minh-Phat 24 carats gold leaf, French Cochinchina (Undated).png"]),
    V("kim-hoang", "Làng tranh Kim Hoàng", "Hà Nội", "Hoài Đức", "Vân Canh", 21.058, 105.735,
      "tranh", "Tranh dân gian", "Nguyễn Thị Thoa",
      "Tranh dân gian Kim Hoàng in trên giấy đỏ",
      "Dòng tranh Tết in mộc bản trên nền giấy hồng điều, từng thất truyền và đang được phục dựng.",
      at=["Lon doc.jpg", "Ga doc.JPG"]),
    V("lien-ha", "Làng mộc Liên Hà", "Hà Nội", "Đông Anh", "Liên Hà", 21.135, 105.885,
      "do-go", "Đồ gỗ nội thất", "Đỗ Văn Hùng",
      "Bàn ghế, tủ thờ gỗ Liên Hà",
      "Làng mộc lớn phía bắc Hà Nội chuyên đồ gỗ nội thất và đồ thờ, nhiều xưởng làm theo đơn đặt hàng.",
      illus=["Altar in the shape of a chair, Nguyen dynasty, 19th to early 20th century, crimson and gilded wood, view 1 - National Museum of Vietnamese History - Hanoi, Vietnam - DSC05625.JPG"]),
    # ── Bắc Ninh – Bắc Giang – Vĩnh Phúc – Phú Thọ ───────────────────────────
    V("duong-o", "Làng giấy dó Dương Ổ", "Bắc Ninh", "Bắc Ninh", "Phong Khê", 21.198, 106.045,
      "giay-do", "Giấy dó, giấy điệp", "Phạm Văn Tú",
      "Giấy dó và giấy điệp Dương Ổ",
      "Làng xeo giấy dó thủ công từ vỏ cây dó, làm ra giấy điệp dùng in tranh Đông Hồ và viết thư pháp.",
      illus=["Kreado de pentraĵo en vilaĝo Đông Hồ 01.jpg",
             "Picture of giving lecture, Doc Loi temple, Nghe An province, late 18th century, Do (poonah) paper - Vietnam National Museum of Fine Arts - Hanoi, Vietnam - DSC05107.JPG"]),
    V("dai-bai", "Làng gò đồng Đại Bái", "Bắc Ninh", "Gia Bình", "Đại Bái", 21.043, 106.212,
      "do-dong", "Đồ đồng gò", "Nguyễn Văn Đạt",
      "Đồ đồng gò Đại Bái — mâm, đỉnh, tranh đồng",
      "Làng gò đồng gần nghìn năm: thợ dùng búa gò đồng lá thành mâm, nồi, đỉnh hương và tranh đồng "
      "chạm nổi.",
      illus=["Đúc đồng.jpg",
             "Incense burner, Nguyen dynasty, 19th to early 20th century, bronze - National Museum of Vietnamese History - Hanoi, Vietnam - DSC05600.JPG"]),
    V("phu-lang", "Làng gốm Phù Lãng", "Bắc Ninh", "Quế Võ", "Phù Lãng", 21.170, 106.238,
      "gom-su", "Gốm sành nâu", "Vũ Văn Lập",
      "Gốm men da lươn Phù Lãng",
      "Làng gốm bên sông Cầu nổi tiếng với men nâu da lươn và gốm đắp nổi; lò nung củi vẫn còn hoạt động.",
      at=["Đồ gốm Phù Lãng.jpg", "Xưởng gốm Phù Lãng.jpg", "Lò nung gốm Phù Lãng.jpg"]),
    V("dong-ky", "Làng mộc Đồng Kỵ", "Bắc Ninh", "Từ Sơn", "Đồng Kỵ", 21.140, 105.952,
      "do-go", "Đồ gỗ mỹ nghệ", "Nguyễn Văn Đông",
      "Đồ gỗ mỹ nghệ Đồng Kỵ",
      "Làng mộc mỹ nghệ sầm uất bậc nhất miền Bắc với sập, tủ, salon chạm khắc; lễ hội làng đầu xuân "
      "nổi tiếng với tục rước pháo.",
      at=["Đồng Kỵ 02.jpg", "Đồng Kỵ 06.jpg"],
      illus=["Nguyen Dynasty, 19th-20th Century Carved Wood Panels (9735489759).jpg"]),
    V("xuan-lai", "Làng mây tre Xuân Lai", "Bắc Ninh", "Gia Bình", "Xuân Lai", 21.058, 106.230,
      "may-tre", "Mây tre đan", "Nguyễn Thị Hiền",
      "Đèn tre và đồ mây tre đan Xuân Lai",
      "Làng mây tre đan cổ của Bắc Ninh: nong, nia, giỏ, đèn trang trí và đồ nội thất từ tre, mây, giang.",
      at=["Đèn tre Xuân Lai - panoramio.jpg"]),
    V("phu-khe", "Làng chạm gỗ Phù Khê", "Bắc Ninh", "Từ Sơn", "Phù Khê", 21.152, 105.938,
      "cham-khac", "Chạm khắc gỗ", "Nguyễn Văn Khải",
      "Đồ gỗ chạm khắc Phù Khê",
      "Làng chạm khắc gỗ nổi tiếng với kỹ thuật chạm lộng, chạm bong trên tranh, tượng và đồ nội thất.",
      illus=["Lamp stand in the shape of 'bamboo transforming into dragon' and auspicious animals, for ritual use, early 20th century, carved wood - National Museum of Vietnamese History - Hanoi, Vietnam - DSC05573.JPG",
             "Decoration for hammock holder, Nguyen dynasty, 19th to early 20th century, crimson and gilded wood - National Museum of Vietnamese History - Hanoi, Vietnam - DSC05618.JPG"]),
    V("huong-mac", "Làng gỗ Hương Mạc", "Bắc Ninh", "Từ Sơn", "Hương Mạc", 21.158, 105.922,
      "do-go", "Đồ gỗ mỹ nghệ", "Ngô Văn Tình",
      "Tủ, sập, kệ gỗ mỹ nghệ Hương Mạc",
      "Làng mộc mỹ nghệ cạnh Đồng Kỵ, chuyên đồ gỗ cao cấp chạm khắc và khảm trai.",
      illus=["Temple furnishings in crimson and gold, Museum of Vietnamese History, Hanoi (4) (38467125602).jpg"]),
    V("tho-ha", "Làng gốm Thổ Hà", "Bắc Giang", "Việt Yên", "Vân Hà", 21.215, 106.030,
      "gom-su", "Gốm sành", "Ngô Văn Thuận",
      "Gốm sành Thổ Hà và làng cổ bên sông Cầu",
      "Làng cổ bên sông Cầu với cổng làng, đình làng và nghề gốm sành nung không men từng nổi tiếng "
      "khắp xứ Kinh Bắc.",
      at=["Vietnam - Tho Ha Ancient Village.jpg", "Vietnam - village gate of Tho Ha.jpg",
          "Incense burner, Tho Ha ceramic, earthenware - Nguyen dynasty, 19th century AD - Vietnam National Museum of Fine Arts - Hanoi, Vietnam - DSC05331.JPG"]),
    V("tang-tien", "Làng mây tre Tăng Tiến", "Bắc Giang", "Việt Yên", "Tăng Tiến", 21.268, 106.088,
      "may-tre", "Mây tre giang đan", "Thân Văn Hòa",
      "Hàng mây tre giang đan Tăng Tiến",
      "Làng mây tre đan xuất khẩu lớn của Bắc Giang: giỏ, hộp, khay đan từ giang, mây, guột.",
      illus=["Vietnam - Making baskets.jpg", "Basket Maker Vietnam.jpg"]),
    V("huong-canh", "Làng gốm Hương Canh", "Vĩnh Phúc", "Bình Xuyên", "Hương Canh", 21.272, 105.650,
      "gom-su", "Gốm sành", "Nguyễn Văn Nghĩa",
      "Chum, vại, tiểu sành Hương Canh",
      "Làng gốm sành nổi tiếng với chum, vại, chậu cảnh nung già lửa, gõ vào kêu như chuông.",
      illus=["Jar, Later Le Dynasty, Red River Delta, Vietnam, 15th Century (10433594223).jpg",
             "Water container, earthenware - Nguyen dynasty, 19th century AD - Vietnam National Museum of Fine Arts - Hanoi, Vietnam - DSC05297.JPG"]),
    V("bich-chu", "Làng mộc Bích Chu", "Vĩnh Phúc", "Vĩnh Tường", "An Tường", 21.230, 105.530,
      "do-go", "Đồ gỗ", "Lê Văn Thành",
      "Đồ mộc dân dụng và đình chùa Bích Chu",
      "Làng mộc lâu đời, thợ Bích Chu từng tham gia dựng nhiều đình chùa cổ; nay làm đồ gỗ nội thất và đồ thờ.",
      illus=["Temple furnishings in crimson and gold, Museum of Vietnamese History, Hanoi (2) (24627170538).jpg"]),
    V("sai-nga", "Làng nón Sai Nga", "Phú Thọ", "Cẩm Khê", "Sai Nga", 21.402, 105.112,
      "may-tre", "Nón lá", "Nguyễn Thị Liên",
      "Nón lá Sai Nga khâu từ lá cọ",
      "Làng làm nón lá cọ trăm năm tuổi ở vùng trung du, nón khâu tay nhiều lớp, bền và nhẹ.",
      illus=["Conical hat 01.jpg", "Conical hats 04.jpg"]),
    # ── Đồng bằng sông Hồng ──────────────────────────────────────────────────
    V("dong-xam", "Làng chạm bạc Đồng Xâm", "Thái Bình", "Kiến Xương", "Hồng Thái", 20.422, 106.422,
      "kim-hoan", "Chạm bạc", "Phạm Văn Đức",
      "Đồ bạc chạm Đồng Xâm",
      "Cái nôi nghề chạm bạc của Việt Nam; đền Đồng Xâm thờ tổ nghề, thợ làng chạm hộp, khay, trang sức "
      "bằng kỹ thuật chạm nổi, chạm thủng.",
      at=["Đền Đồng Xâm thập niên 1920 (1920's Dong Xam Temple) - Ảnh màu.jpg"],
      illus=["Silver box.jpg"]),
    V("phuong-la", "Làng dệt Phương La", "Thái Bình", "Hưng Hà", "Thái Phương", 20.582, 106.240,
      "lua", "Dệt khăn, vải", "Trần Thị Nhung",
      "Khăn, vải dệt Phương La",
      "Làng dệt truyền thống của Thái Bình chuyên khăn bông, vải đũi; nhiều hộ còn giữ khung dệt gỗ.",
      illus=["Weaver and loom, Muong - Vietnam Museum of Ethnology - Hanoi, Vietnam - DSC02730.JPG", "Silk weaving, 2003 Ha Dong 2.jpg"]),
    V("minh-lang", "Làng thêu Minh Lãng", "Thái Bình", "Vũ Thư", "Minh Lãng", 20.452, 106.282,
      "theu", "Tranh thêu", "Vũ Thị Hạnh",
      "Tranh thêu tay Minh Lãng",
      "Làng thêu ren xuất khẩu của Thái Bình; tranh thêu phong cảnh và chân dung làm thủ công tỉ mỉ.",
      illus=["Commissioned embroidery by Vũ Ngọc Hoánh, Chief of Lạng Sơn Province 02.jpg", "TissusVietnam 0335.JPG"]),
    V("chieu-hoi", "Làng chiếu Hới", "Thái Bình", "Hưng Hà", "Tân Lễ", 20.628, 106.152,
      "coi-luc-binh", "Chiếu cói", "Đào Văn Hậu",
      "Chiếu cói Hới dệt hoa",
      "Chiếu Hới nổi tiếng bền, đẹp, dệt hoa văn nhuộm phẩm; từng là chiếu tiến vua và đồ cưới không thể thiếu.",
      at=["Hoi village's sedge weaving mat in temple of Trần dynasty (Trang An, Ninh Binh).jpg",
          "Lang Hoi sedge weaving mat in temple of Trần dynasty (Trang An, Ninh Binh) 2.jpg"]),
    V("tong-xa", "Làng đúc đồng Tống Xá", "Nam Định", "Ý Yên", "Yên Xá", 20.322, 106.022,
      "do-dong", "Đồ đồng đúc", "Nguyễn Văn Định",
      "Chuông, tượng, đỉnh đồng Tống Xá",
      "Làng đúc đồng lớn của Nam Định: chuông, tượng, đỉnh, đồ thờ cỡ lớn đúc theo khuôn đất truyền thống.",
      illus=["Bells - National Museum of Vietnamese History - Hanoi, Vietnam - DSC05644.JPG"]),
    V("la-xuyen", "Làng mộc La Xuyên", "Nam Định", "Ý Yên", "Yên Ninh", 20.335, 106.038,
      "do-go", "Đồ gỗ chạm khắc", "Phạm Văn Kiên",
      "Đồ gỗ chạm khắc La Xuyên",
      "Làng mộc trên dưới 800 năm, nổi tiếng với kỹ thuật chạm khắc, khảm trai; đình làng còn giữ nhiều "
      "mảng chạm cổ.",
      at=["Đình La Xuyên, cây đa.JPG"],
      illus=["Altar in the shape of a chair, Nguyen dynasty, 19th to early 20th century, crimson and gilded wood, view 2 - National Museum of Vietnamese History - Hanoi, Vietnam - DSC05626.JPG"]),
    V("cat-dang", "Làng sơn mài Cát Đằng", "Nam Định", "Ý Yên", "Yên Tiến", 20.302, 106.045,
      "son-mai", "Sơn mài", "Trần Văn Hòa",
      "Đồ sơn mài và sơn son thếp vàng Cát Đằng",
      "Làng sơn truyền thống, thợ Cát Đằng nổi tiếng với kỹ thuật sơn son thếp vàng đồ thờ và tranh sơn mài.",
      illus=["Hanoi-Application de nacre sur la laque (1).jpg", "Hanoi-Rinçage de l'objet laqué (1).jpg"]),
    V("van-lam", "Làng thêu ren Văn Lâm", "Ninh Bình", "Hoa Lư", "Ninh Hải", 20.222, 105.930,
      "theu", "Thêu ren", "Đinh Thị Lan",
      "Thêu ren Văn Lâm trong lòng Tam Cốc",
      "Làng thêu ren tương truyền có từ thời Trần, nằm ngay khu du lịch Tam Cốc – Bích Động; khăn, áo, "
      "tranh thêu bán cho du khách.",
      illus=["TissusVietnam 0337.JPG", "TissusVietnam 0339.JPG"]),
    V("ninh-van", "Làng đá Ninh Vân", "Ninh Bình", "Hoa Lư", "Ninh Vân", 20.198, 105.892,
      "da-my-nghe", "Đá mỹ nghệ", "Đinh Văn Tuấn",
      "Đá mỹ nghệ Ninh Vân — tượng, lan can, cổng đá",
      "Làng chạm khắc đá lớn nhất miền Bắc; thợ Ninh Vân tạc tượng, lăng mộ, cổng và lan can đá cho "
      "nhiều công trình.",
      illus=["Dragon claw details in Da Nang.jpg"]),
    V("kim-son", "Làng cói Kim Sơn", "Ninh Bình", "Kim Sơn", "Phát Diệm", 20.088, 106.082,
      "coi-luc-binh", "Cói mỹ nghệ", "Vũ Văn Hưng",
      "Chiếu, thảm, giỏ cói Kim Sơn",
      "Vùng cói lớn của đồng bằng Bắc Bộ: cói trồng ven biển được dệt thành chiếu, thảm, giỏ, hộp xuất khẩu.",
      illus=["Sedge mat manufacture 01.jpg", "Sedge mat manufacture 02.jpg"]),
    V("nha-xa", "Làng lụa Nha Xá", "Hà Nam", "Duy Tiên", "Mộc Nam", 20.618, 105.992,
      "lua", "Lụa tơ tằm", "Trần Thị Hương",
      "Lụa tơ tằm Nha Xá bên sông Hồng",
      "Làng dệt lụa hơn 700 năm bên sông Hồng; lụa Nha Xá mềm, bóng, được nhuộm và may thành khăn, áo dài.",
      illus=["Silk weaving, 2003 Ha Dong 6.jpg", "Silk weaving, 2003 Ha Dong 9.jpg"]),
    V("doi-tam", "Làng trống Đọi Tam", "Hà Nam", "Duy Tiên", "Đọi Sơn", 20.578, 105.962,
      "do-go", "Trống da", "Nguyễn Văn Trọng",
      "Trống da Đọi Tam — trống hội, trống trường",
      "Làng làm trống nổi tiếng nhất miền Bắc: tang gỗ mít, mặt da trâu; trống Đọi Tam vang trong nhiều "
      "lễ hội và sự kiện lớn.",
      illus=["Chùa Linh Quang (trống đại) (1).jpg", "MIMVietnamDrum.jpg"]),
    V("ngoc-dong", "Làng mây giang đan Ngọc Động", "Hà Nam", "Duy Tiên", "Hoàng Đông", 20.602, 105.978,
      "may-tre", "Mây giang đan", "Lê Thị Nga",
      "Hàng mây giang đan Ngọc Động",
      "Làng nghề mây giang đan xuất khẩu, đình làng cổ là nơi thờ tổ nghề đan.",
      at=["Đình Ngọc Động.jpg"],
      illus=["Basket made of varnished and closely-fitted bamboo, Nam Dinh province - Vietnam National Museum of Fine Arts - Hanoi, Vietnam - DSC05247.JPG"]),
    V("an-hoa", "Làng thêu ren An Hòa", "Hà Nam", "Thanh Liêm", "Thanh Hà", 20.452, 105.918,
      "theu", "Thêu ren", "Phạm Thị Duyên",
      "Khăn trải bàn, gối thêu ren An Hòa",
      "Làng thêu ren xuất khẩu của Hà Nam với khăn, gối, rèm thêu móc tay.",
      illus=["Tranh thêu Đà Lạt.jpg", "TissusVietnam 0341.JPG"]),
    V("chau-khe", "Làng kim hoàn Châu Khê", "Hải Dương", "Bình Giang", "Thúc Kháng", 20.862, 106.172,
      "kim-hoan", "Vàng bạc", "Lưu Văn Thành",
      "Trang sức vàng bạc Châu Khê",
      "Quê tổ nghề kim hoàn; thợ Châu Khê từng lập phường Hàng Bạc ở Thăng Long và giữ nghề đúc, chạm "
      "vàng bạc đến nay.",
      illus=["Vietnamese Women's Museum, Hmong Silver earrings.jpg",
             "Silver pins, bride's dowry, Dao, 1945 - Vietnamese Women's Museum - Hanoi, Vietnam - DSC04372.JPG"]),
    V("dong-giao", "Làng chạm gỗ Đông Giao", "Hải Dương", "Cẩm Giàng", "Lương Điền", 20.962, 106.198,
      "cham-khac", "Chạm khắc gỗ", "Nguyễn Văn Giao",
      "Hoành phi, tượng, bình phong chạm gỗ Đông Giao",
      "Làng chạm khắc gỗ lâu đời với hoành phi, câu đối, tượng, đồ thờ chạm tay tinh xảo.",
      illus=["Nguyen Dynasty, 19th-20th Century Carved Wood Panels (9738957480).jpg"]),
    V("gom-cay", "Làng gốm Cậy", "Hải Dương", "Bình Giang", "Long Xuyên", 20.888, 106.248,
      "gom-su", "Gốm men", "Vũ Văn Cường",
      "Gốm men lam Cậy",
      "Làng gốm cổ cùng hệ với Chu Đậu, nổi tiếng gốm men lam và men rạn; đang được phục hồi.",
      illus=["Chùa Giác Lâm, tháng 01 năm 2022 (bình gốm quý men lam) (1).jpg",
             "Chùa Hộ Quốc (lộc bình gốm men lam) (1).jpg"]),
    V("bao-ha", "Làng tạc tượng Bảo Hà", "Hải Phòng", "Vĩnh Bảo", "Đồng Minh", 20.702, 106.468,
      "tuong", "Tượng gỗ", "Đỗ Văn Bảo",
      "Tượng gỗ Bảo Hà — tượng Phật, tượng thờ, con rối",
      "Làng tạc tượng và rối nước nổi tiếng đất Cảng; tượng Bảo Hà có mặt ở nhiều đình chùa miền Bắc.",
      illus=["Pair of lion statues,, 19th century, Museum of Vietnamese History, Hanoi (38443771936).jpg",
             "Buddha, Kien Xuong district, Thai Binh province, 19th century AD, wood - Vietnam National Museum of Fine Arts - Hanoi, Vietnam - DSC05101.JPG"]),
    V("my-dong", "Làng đúc Mỹ Đồng", "Hải Phòng", "Thủy Nguyên", "Mỹ Đồng", 20.928, 106.648,
      "do-dong", "Đồ đồng đúc", "Phạm Văn Đồng",
      "Đồ đồng đúc Mỹ Đồng",
      "Làng đúc đồng và kim loại truyền thống của Hải Phòng, làm chuông, khánh và đồ thờ.",
      illus=["Khánh cổ bằng đồng.jpg"]),
    V("dong-trieu", "Làng gốm Đông Triều", "Quảng Ninh", "Đông Triều", "Đức Chính", 21.072, 106.548,
      "gom-su", "Gốm sứ", "Hoàng Văn Thái",
      "Gốm Đông Triều — chum, chậu, bình",
      "Vùng gốm có từ thời Trần với các lò nung lớn, chuyên chum vại, chậu cảnh và gốm mỹ nghệ.",
      at=["Fours de cuisson (Dong Trieu) (4375854466).jpg",
          "Façonnage dobjets en céramique (Dong Trieu) (4375104361).jpg",
          "Façonnage dobjets en céramique (Dong Trieu) (4375855054).jpg"]),
    # ── Bắc Trung Bộ ─────────────────────────────────────────────────────────
    V("nga-son", "Làng chiếu cói Nga Sơn", "Thanh Hóa", "Nga Sơn", "Nga Văn", 19.998, 105.968,
      "coi-luc-binh", "Chiếu cói", "Mai Thị Hoa",
      "Chiếu cói Nga Sơn dệt hoa",
      "Chiếu Nga Sơn nổi tiếng khắp cả nước; cói trồng trên đất bãi bồi ven biển, dệt thành chiếu hoa, "
      "thảm, túi xách.",
      illus=["Sedge mat manufacture 03.jpg",
             "Traditional lying down-style sedge mat weaving in Vietnam, two people weaving phase, unknown location.png"]),
    V("tra-dong", "Làng đúc đồng Trà Đông", "Thanh Hóa", "Thiệu Hóa", "Thiệu Trung", 19.888, 105.682,
      "do-dong", "Đồ đồng đúc", "Lê Văn Đông",
      "Trống đồng, chuông, đỉnh đúc Trà Đông",
      "Làng đúc đồng xứ Thanh nổi tiếng với trống đồng phục chế, chuông và đồ thờ đúc khuôn đất.",
      illus=["Khánh đồng Mông Phụ.jpg"]),
    V("da-nhoi", "Làng đá Nhồi", "Thanh Hóa", "Đông Sơn", "Đông Hưng", 19.792, 105.812,
      "da-my-nghe", "Đá mỹ nghệ", "Lê Văn Hồi",
      "Đá mỹ nghệ núi Nhồi",
      "Làng chế tác đá dưới chân núi Nhồi, đá xanh được tạc thành tượng, bia, lăng mộ và đồ trang trí.",
      illus=["Marble Mountain sculpture shop.jpg"]),
    V("lo-chum", "Làng gốm Lò Chum", "Thanh Hóa", "Thanh Hóa", "Hàm Rồng", 19.842, 105.800,
      "gom-su", "Gốm sành", "Lê Thị Châm",
      "Chum, vò, chậu gốm Lò Chum",
      "Làng gốm cổ dưới chân núi Hàm Rồng bên sông Mã, chuyên chum, vò, chậu đất nung.",
      illus=["Earthenware pots (9980421915).jpg",
             "Jar, Tran dynasty, 14th century AD, stoneware - Museum of Vietnamese History - Ho Chi Minh City - DSC06204.JPG"]),
    V("phuong-lich", "Làng dệt Phương Lịch", "Nghệ An", "Diễn Châu", "Diễn Hoa", 18.982, 105.598,
      "lua", "Dệt vải, lụa", "Hồ Thị Lịch",
      "Vải và lụa dệt Phương Lịch",
      "Làng dệt truyền thống xứ Nghệ, xưa nổi tiếng vải lụa trắng, nay dệt khăn và vải thủ công.",
      illus=["Silk weaving, 2003 Ha Dong 15.jpg", "Silk weaving, 2003 Ha Dong 19.jpg"]),
    V("thai-yen", "Làng mộc Thái Yên", "Hà Tĩnh", "Đức Thọ", "Thái Yên", 18.532, 105.618,
      "do-go", "Đồ gỗ", "Trần Văn Yên",
      "Đồ mộc mỹ nghệ Thái Yên",
      "Làng mộc nổi tiếng xứ Nghệ Tĩnh, thợ Thái Yên làm nhà rường, đồ thờ và đồ gỗ chạm khắc.",
      illus=["Temple furnishings in crimson and gold, Museum of Vietnamese History, Hanoi (3) (37612655825).jpg"]),
    V("thanh-tien", "Làng hoa giấy Thanh Tiên", "Thừa Thiên Huế", "Phú Vang", "Phú Mậu", 16.508, 107.602,
      "giay-do", "Hoa giấy", "Thân Văn Tiến",
      "Hoa giấy Thanh Tiên dùng thờ cúng ngày Tết",
      "Làng làm hoa giấy hơn 300 năm của xứ Huế; hoa sen, hoa cúc giấy nhiều màu dùng thờ cúng dịp Tết.",
      at=["Hoa giay Thanh Tien.JPG"]),
    V("tranh-sinh", "Làng tranh Sình", "Thừa Thiên Huế", "Phú Vang", "Phú Mậu", 16.522, 107.578,
      "tranh", "Tranh dân gian", "Kỳ Văn Sinh",
      "Tranh làng Sình in mộc bản tô màu tay",
      "Dòng tranh dân gian xứ Huế in từ ván khắc, tô màu bằng tay, chủ yếu dùng trong thờ cúng.",
      at=["Tranh lang sinh.JPG"]),
    V("non-tay-ho", "Làng nón Tây Hồ", "Thừa Thiên Huế", "Phú Vang", "Phú Hồ", 16.478, 107.662,
      "may-tre", "Nón bài thơ", "Nguyễn Thị Hồ",
      "Nón bài thơ Huế",
      "Làng nón lá xứ Huế với nón bài thơ — giữa hai lớp lá kẹp hình cắt và câu thơ, soi lên nắng mới thấy.",
      illus=["Making conical hats - Hue countryside.jpg"]),
    V("phuong-duc", "Làng đúc đồng Phường Đúc", "Thừa Thiên Huế", "Huế", "Phường Đúc", 16.448, 107.560,
      "do-dong", "Đồ đồng đúc", "Nguyễn Văn Đúc",
      "Chuông, tượng, đỉnh đồng Phường Đúc",
      "Phường đúc từ thời chúa Nguyễn, nơi đúc súng thần công và đỉnh đồng Hoàng cung; nay đúc chuông, "
      "tượng, đồ thờ.",
      at=["Street in Phường Đúc.jpg"],
      illus=["Bell for ritual use (replica), Thanh Mai pagoda, Ha Tay province, cast in 798 AD, bronze - National Museum of Vietnamese History - Hanoi, Vietnam - DSC05548.JPG"]),
    V("ke-mon", "Làng kim hoàn Kế Môn", "Thừa Thiên Huế", "Phong Điền", "Điền Môn", 16.622, 107.372,
      "kim-hoan", "Vàng bạc", "Cao Văn Môn",
      "Trang sức vàng bạc Kế Môn",
      "Làng kim hoàn nổi tiếng miền Trung; thợ Kế Môn có mặt ở nhiều tiệm vàng khắp cả nước.",
      illus=["Lập lắc (vòng xuyến đeo cổ và đeo tay) nạp tài (1).jpg"]),
    V("bao-la", "Làng mây tre Bao La", "Thừa Thiên Huế", "Quảng Điền", "Quảng Phú", 16.552, 107.532,
      "may-tre", "Mây tre đan", "Trần Thị La",
      "Đồ mây tre đan Bao La",
      "Làng mây tre đan lâu đời của xứ Huế với rổ, rá, giỏ và đồ nội thất từ tre, mây.",
      at=["Dinh Bao La 1.JPG"],
      illus=["Sản phẩm Mây tre đan Trà.jpg"]),
    # ── Nam Trung Bộ & Tây Nguyên ────────────────────────────────────────────
    V("thanh-ha", "Làng gốm Thanh Hà", "Quảng Nam", "Hội An", "Thanh Hà", 15.882, 108.302,
      "gom-su", "Gốm đất nung", "Lê Văn Hà",
      "Gốm Thanh Hà — đất nung và còi gốm",
      "Làng gốm 500 năm bên sông Thu Bồn, cạnh phố cổ Hội An; nổi tiếng gốm đất nung đỏ, còi gốm hình con giáp.",
      at=["Sản phẩm làng gốm Thanh Hà.JPG", "Nghệ nhân làng gốm Thanh Hà.JPG",
          "Con thổi - Làng gốm Thanh Hà, Hội An, Việt Nam.jpg"]),
    V("ma-chau", "Làng lụa Mã Châu", "Quảng Nam", "Duy Xuyên", "Nam Phước", 15.815, 108.255,
      "lua", "Lụa tơ tằm", "Đoàn Thị Châu",
      "Lụa tơ tằm Mã Châu",
      "Làng dệt lụa có từ thế kỷ 16 bên sông Thu Bồn; lụa Mã Châu từng theo thương thuyền qua cảng Hội An.",
      illus=["Satin mã châu 2.jpg", "Rio mã châu áo tấc.jpg"]),
    V("zara", "Làng dệt thổ cẩm Zara", "Quảng Nam", "Nam Giang", "Tà Bhing", 15.648, 107.612,
      "tho-cam", "Thổ cẩm Cơ Tu", "Zơ Râm Thị Bríu",
      "Thổ cẩm Cơ Tu đính hạt cườm",
      "Làng dệt thổ cẩm của người Cơ Tu, nổi bật kỹ thuật đính hạt cườm vào hoa văn; vải Zara từng được "
      "trao chứng nhận sản phẩm thủ công tiêu biểu.",
      illus=["Salet, Katu hunter basket.jpg", "House model, Co Tu - Vietnam Museum of Ethnology - Hanoi, Vietnam - DSC03305.JPG"]),
    V("phuoc-kieu", "Làng đúc đồng Phước Kiều", "Quảng Nam", "Điện Bàn", "Điện Phương", 15.842, 108.252,
      "do-dong", "Chiêng, đồ đồng", "Dương Văn Kiều",
      "Chiêng, chuông, đồ đồng Phước Kiều",
      "Làng đúc đồng 400 năm, nổi tiếng chiêng có âm thanh chuẩn cho đồng bào Tây Nguyên và đồ thờ.",
      at=["Làng Đúc đồng Phước Kiều, Điện Bàn, Quảng Nam.jpeg"],
      illus=["Bộ cồng chiêng.jpg"]),
    V("ban-thach", "Làng chiếu Bàn Thạch", "Quảng Nam", "Duy Xuyên", "Duy Vinh", 15.802, 108.292,
      "coi-luc-binh", "Chiếu cói", "Nguyễn Thị Thạch",
      "Chiếu cói Bàn Thạch",
      "Làng dệt chiếu ven sông Thu Bồn, chiếu cói dệt khung gỗ, nhuộm hoa văn truyền thống.",
      illus=["Cụ ông bán chiếu cói, năm 1900.jpg"]),
    V("cam-ne", "Làng chiếu Cẩm Nê", "Đà Nẵng", "Hòa Vang", "Hòa Tiến", 15.968, 108.132,
      "coi-luc-binh", "Chiếu cói", "Lê Thị Nê",
      "Chiếu cói Cẩm Nê",
      "Làng chiếu xứ Quảng hơn trăm năm, gắn với lễ hội và đặc sản bánh tráng Cẩm Lệ – Cẩm Nê.",
      illus=["Butiko en Hanojo.jpg"]),
    V("phu-gia", "Làng nón ngựa Phú Gia", "Bình Định", "Phù Cát", "Cát Tường", 13.978, 109.082,
      "may-tre", "Nón ngựa", "Võ Văn Gia",
      "Nón ngựa Phú Gia — nón quan xưa",
      "Nón ngựa xưa dành cho quan lại cưỡi ngựa, làm cầu kỳ với lá kè, sườn tre và chỉ thêu hoa văn.",
      illus=["Hat, Viet, Binh Dinh, 1986, palm leaves with bamboo frame, wool patterns - Vietnamese Women's Museum - Hanoi, Vietnam - DSC04000.JPG", "Hatter Vietnam.jpg"]),
    V("tam-quan", "Làng thảm xơ dừa Tam Quan", "Bình Định", "Hoài Nhơn", "Tam Quan", 14.572, 109.052,
      "coi-luc-binh", "Thảm xơ dừa", "Huỳnh Văn Quan",
      "Thảm và dây xơ dừa Tam Quan",
      "Xứ dừa Tam Quan làm thảm, dây và đồ thủ công từ xơ dừa; sản phẩm được xuất khẩu.",
      illus=["Coir fibery.jpg"]),
    V("lu-cam", "Làng gốm Lư Cấm", "Khánh Hòa", "Nha Trang", "Ngọc Hiệp", 12.268, 109.172,
      "gom-su", "Gốm đất nung", "Trần Văn Cấm",
      "Gốm đất nung Lư Cấm",
      "Làng gốm cổ bên sông Cái Nha Trang, làm nồi, ơ, chậu đất nung; đang được phục hồi gắn với du lịch.",
      illus=["Tree pot, 1 of 2, earthenware - Nguyen dynasty, 19th century AD - Vietnam National Museum of Fine Arts - Hanoi, Vietnam - DSC05293.JPG", "Tree pot, 2 of 2, earthenware - Nguyen dynasty, 19th century AD - Vietnam National Museum of Fine Arts - Hanoi, Vietnam - DSC05294.JPG"]),
    V("my-nghiep", "Làng dệt Mỹ Nghiệp", "Ninh Thuận", "Ninh Phước", "Phước Dân", 11.528, 108.938,
      "tho-cam", "Thổ cẩm Chăm", "Lưu Thị Nghiệp",
      "Thổ cẩm Chăm Mỹ Nghiệp",
      "Làng dệt thổ cẩm của người Chăm cạnh Bàu Trúc, dệt khung tay với hoa văn hình học đặc trưng.",
      illus=["Costume, Cham, An Giang, 1956, view 1, brocade with silk skirt - Vietnamese Women's Museum - Hanoi, Vietnam - DSC04092.JPG"]),
    V("binh-duc", "Làng gốm Bình Đức", "Bình Thuận", "Bắc Bình", "Phan Hiệp", 11.232, 108.468,
      "gom-su", "Gốm Chăm", "Đàng Văn Đức",
      "Gốm Chăm Bình Đức nặn tay",
      "Làng gốm Chăm nặn tay không bàn xoay, nung lộ thiên; cùng Bàu Trúc thuộc di sản nghệ thuật làm "
      "gốm của người Chăm.",
      illus=["Water container, earthenware - Nguyen dynasty, 19th century AD - Vietnam National Museum of Fine Arts - Hanoi, Vietnam - DSC05296.JPG"]),
    V("lach-duong", "Làng thổ cẩm Lạch Dương", "Lâm Đồng", "Lạc Dương", "Lạc Dương", 12.002, 108.428,
      "tho-cam", "Thổ cẩm K'Ho", "Kră Jăn Ha Mai",
      "Thổ cẩm K'Ho dệt khung tay dưới chân Lang Biang",
      "Làng dệt thổ cẩm của người K'Ho Lạch dưới chân núi Lang Biang, dệt bằng khung đeo lưng.",
      illus=["Back loom, Co-ho, Lat, Lac Duong, Lam Dong, 1994 - Vietnamese Women's Museum - Hanoi, Vietnam - DSC04306.JPG"]),
    V("ako-dhong", "Buôn Ako Dhông", "Đắk Lắk", "Buôn Ma Thuột", "Tân Lợi", 12.698, 108.058,
      "tho-cam", "Thổ cẩm Ê Đê", "H'Lim Byă",
      "Thổ cẩm Ê Đê buôn Ako Dhông",
      "Buôn văn hoá của người Ê Đê giữa lòng Buôn Ma Thuột với nhà dài truyền thống, nghề dệt thổ cẩm "
      "và ủ rượu cần.",
      at=["Buon ako dhong.JPG", "Buon ako dhong khu sinh thai 1.JPG"]),
    V("kon-ktu", "Làng Kon Kơ Tu", "Kon Tum", "Kon Tum", "Đăk Rơ Wa", 14.318, 108.048,
      "tho-cam", "Thổ cẩm Ba Na", "Y Blơng",
      "Thổ cẩm Ba Na làng Kon Kơ Tu",
      "Làng du lịch cộng đồng của người Ba Na bên sông Đăk Bla, giữ nhà rông, nghề dệt thổ cẩm và đan lát.",
      illus=["Belted child's apron, Ba Na - Vietnam Museum of Ethnology - Hanoi, Vietnam - DSC03266.JPG", "Nhà Rông người Ba Na (Mặt trước).jpg"]),
    # ── Miền núi phía Bắc ─────────────────────────────────────────────────────
    V("lung-tam", "Làng dệt lanh Lùng Tám", "Hà Giang", "Quản Bạ", "Quản Bạ", 23.068, 105.038,
      "tho-cam", "Vải lanh Mông", "Thào Thị Sính",
      "Vải lanh Mông Lùng Tám vẽ sáp ong",
      "Hợp tác xã dệt lanh của phụ nữ Mông: trồng lanh, tước sợi, dệt vải, vẽ sáp ong và nhuộm chàm thủ công.",
      illus=["Costume, Hmong Trang, Ha Giang, 1980, hemp and cotton - Vietnamese Women's Museum - Hanoi, Vietnam - DSC03793.JPG", "Skirt (AM 2007.68.1-1).jpg"]),
    V("cat-cat", "Bản Cát Cát", "Lào Cai", "Sa Pa", "Sa Pa", 22.328, 103.832,
      "tho-cam", "Thổ cẩm Mông", "Giàng Thị Mỷ",
      "Thổ cẩm và đồ thêu Mông bản Cát Cát",
      "Bản người Mông dưới thung lũng Mường Hoa, giữ nghề dệt vải lanh, nhuộm chàm, thêu và chạm bạc.",
      at=["Water wheel in Cat Cat village, Sa Pa, Vietnam, 20240126 1142 3546.jpg",
          "Water wheels in Cat Cat village, Sa Pa, Vietnam, 20240126 1220 3606.jpg"],
      illus=["Batik, Hmong (Hmong Hoa) - Vietnam Museum of Ethnology - Hanoi, Vietnam - DSC03046.JPG"]),
    V("ta-van", "Bản Tả Van", "Lào Cai", "Sa Pa", "Tả Van", 22.302, 103.882,
      "tho-cam", "Vải nhuộm chàm", "Lò Thị Van",
      "Vải nhuộm chàm, vẽ sáp ong bản Tả Van",
      "Bản của người Giáy và Mông giữa ruộng bậc thang Mường Hoa; phụ nữ nhuộm chàm, vẽ sáp và thêu tay.",
      at=["Sapa Ta Van.jpg", "Rice terraces in Tả Van 01.jpg"],
      illus=["Design drawn on cloth with beeswax prior to dyeing, Hmong (Hong Den) - Vietnam Museum of Ethnology - Hanoi, Vietnam - DSC03036.JPG"]),
    V("ban-lac", "Bản Lác", "Hòa Bình", "Mai Châu", "Chiềng Châu", 20.662, 105.078,
      "tho-cam", "Thổ cẩm Thái", "Hà Thị Lác",
      "Thổ cẩm Thái Trắng bản Lác",
      "Bản người Thái Trắng với nhà sàn giữa cánh đồng Mai Châu; khung cửi dưới gầm sàn dệt khăn, váy, túi "
      "thổ cẩm.",
      at=["Cánh đồng bản Lác.jpg"],
      illus=["Weavin,-Mai-Chau,-Vietnam.jpg", "Traditional-Crafts,-Mai-Chau,-Vietnam.jpg"]),
    V("hua-tat", "Bản Hua Tạt", "Sơn La", "Vân Hồ", "Vân Hồ", 20.818, 104.852,
      "tho-cam", "Thổ cẩm Mông", "Mùa Thị Dua",
      "Vải lanh, thổ cẩm Mông bản Hua Tạt",
      "Bản du lịch cộng đồng của người Mông trên cao nguyên, giữ nghề dệt lanh, thêu và rèn.",
      illus=["Skirt, Hmong Hoa, Tuyen Quang, view 1, 1976, three sewn panels in hemp, major part in batik, embroidered patterns and applique - Vietnamese Women's Museum - Hanoi, Vietnam - DSC03745.JPG", "Batik baby carrier, Hmong - Vietnam Museum of Ethnology - Hanoi, Vietnam - DSC03042.JPG"]),
    V("phja-thap", "Làng hương Phja Thắp", "Cao Bằng", "Nguyên Bình", "Tam Kim", 22.652, 105.942,
      "may-tre", "Hương, giấy bản", "Đặng Văn Thắp",
      "Hương thơm và giấy bản của người Dao Phja Thắp",
      "Làng người Dao làm hương thơm từ vỏ cây, lá rừng và xeo giấy bản thủ công dùng chép sách cúng.",
      illus=["Drying incense 33.jpg", "Drying incense 57.jpg"]),
    # ── Nam Bộ ───────────────────────────────────────────────────────────────
    V("lai-thieu", "Làng gốm Lái Thiêu", "Bình Dương", "Thuận An", "Lái Thiêu", 10.912, 106.702,
      "gom-su", "Gốm sứ", "Lâm Văn Thiêu",
      "Gốm sứ Lái Thiêu vẽ tay",
      "Dòng gốm Nam Bộ hơn 150 năm, nổi tiếng chén, tô, bình men trắng vẽ gà, cá, hoa lá bằng tay.",
      at=["Lai Thieu Ceramics (9997439653).jpg", "Saigon Lai Thieu Ceramics (9997280424).jpg",
          "Rice container, Lai Thieu ceramic, white glaze with cobalt blue patterns - Nguyen dynasty, 19th century AD - Vietnam National Museum of Fine Arts - Hanoi, Vietnam - DSC05303.JPG"]),
    V("tuong-binh-hiep", "Làng sơn mài Tương Bình Hiệp", "Bình Dương", "Thủ Dầu Một", "Tương Bình Hiệp",
      11.012, 106.642, "son-mai", "Sơn mài", "Trần Văn Hiệp",
      "Tranh và đồ sơn mài Tương Bình Hiệp",
      "Làng sơn mài nổi tiếng nhất Nam Bộ, kết hợp khảm trai, cẩn trứng; sản phẩm xuất khẩu nhiều nước.",
      illus=["Hanoi-Application de fragments de coquilles d'oeufs (1).jpg",
             "Lacquered box - Vietnam National Museum of Fine Arts - Hanoi, Vietnam - DSC05246.JPG"]),
    V("phu-an", "Làng tre Phú An", "Bình Dương", "Bến Cát", "Phú An", 11.068, 106.622,
      "may-tre", "Tre đan", "Nguyễn Văn An",
      "Đồ tre đan Phú An",
      "Vùng tre Phú An bên sông Sài Gòn, gắn với nghề đan lát và khu bảo tồn tre trúc.",
      illus=["Sản phẩm từ cây tre.JPG"]),
    V("bien-hoa", "Làng gốm Biên Hòa", "Đồng Nai", "Biên Hòa", "Tân Vạn", 10.918, 106.832,
      "gom-su", "Gốm men", "Lý Văn Hòa",
      "Gốm men xanh đồng trổ Biên Hòa",
      "Dòng gốm Nam Bộ nổi tiếng men xanh đồng trổ và kỹ thuật khắc chìm, đắp nổi; xuất phát từ trường "
      "Mỹ nghệ Biên Hòa đầu thế kỷ 20.",
      at=["Bien Hoa Fine Art Ceramics (9997360933).jpg", "Bien Hoa Fine Art Ceramics (9997592483).jpg",
          "Pot, Bien Hoa ceramic, green glaze - Nguyen dynasty, 19th century AD - Vietnam National Museum of Fine Arts - Hanoi, Vietnam - DSC05305.JPG"]),
    V("buu-long", "Làng đá Bửu Long", "Đồng Nai", "Biên Hòa", "Bửu Long", 10.962, 106.802,
      "da-my-nghe", "Đá mỹ nghệ", "Huỳnh Văn Long",
      "Đá mỹ nghệ Bửu Long",
      "Làng nghề đá có từ thế kỷ 17, chế tác tượng, cối, bia và đồ trang trí từ đá xanh, đá ong.",
      at=["Bửu Long, Bien Hoa, Dong Nai, Vietnam - panoramio (6).jpg"]),
    V("le-minh-xuan", "Làng nhang Lê Minh Xuân", "TP. Hồ Chí Minh", "Bình Chánh", "Lê Minh Xuân", 10.752, 106.532,
      "may-tre", "Nhang thủ công", "Phan Thị Xuân",
      "Nhang thủ công Lê Minh Xuân",
      "Làng nhang ven Sài Gòn, cảnh phơi nhang đỏ rực mỗi dịp cuối năm thu hút người đến chụp ảnh.",
      illus=["Drying incense 21.jpg", "Drying incense 70.jpg"]),
    V("mo-cay", "Làng thủ công dừa Mỏ Cày", "Bến Tre", "Mỏ Cày Nam", "Mỏ Cày", 10.122, 106.332,
      "may-tre", "Đồ thủ công từ dừa", "Nguyễn Văn Dũng",
      "Đồ mỹ nghệ gáo dừa, xơ dừa Bến Tre",
      "Xứ dừa Bến Tre làm đồ mỹ nghệ từ gáo, xơ, thân dừa: chén, muỗng, túi xách, tranh và đồ trang trí.",
      illus=["CoconutPeel @BinhDai BenTre Vietnam.jpg", "Cồn Phụng.jpg"]),
    V("mang-thit", "Làng gốm đỏ Mang Thít", "Vĩnh Long", "Mang Thít", "Mỹ An", 10.198, 106.068,
      "gom-su", "Gốm đỏ", "Trương Văn Thít",
      "Gốm đỏ và gạch nung Mang Thít",
      "\"Vương quốc gốm đỏ\" bên sông Mang Thít với hàng trăm lò gạch, lò gốm hình mái vòm.",
      at=["Lò gạch Mang Thít Vĩnh Long.jpg", "Lò gạch kênh thầy cai- Mang Thít.jpg"]),
    V("dinh-yen", "Làng chiếu Định Yên", "Đồng Tháp", "Lấp Vò", "Định Yên", 10.322, 105.528,
      "coi-luc-binh", "Chiếu lác", "Võ Thị Yên",
      "Chiếu lác Định Yên in hoa",
      "Làng chiếu lớn nhất miền Tây, chợ chiếu họp từ nửa đêm; chiếu lác dệt khung, in hoa văn rực rỡ.",
      at=["Làng chiếu Định Yên.jpg", "Làng chiếu Định Yên,.jpg"]),
    V("van-giao", "Làng thổ cẩm Văn Giáo", "An Giang", "Tịnh Biên", "Văn Giáo", 10.522, 105.032,
      "tho-cam", "Thổ cẩm Khmer", "Néang Sô Phia",
      "Thổ cẩm Khmer Văn Giáo",
      "Làng dệt thổ cẩm của người Khmer vùng Bảy Núi; xà rông, khăn dệt tay hoa văn truyền thống.",
      illus=["Tubular skirt detail, Kho-me, Soc Trang, 1940 - Vietnamese Women's Museum - Hanoi, Vietnam - DSC03906.JPG"]),
]
